# Generated by Django 4.2.5 on 2023-10-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_max_points_assignment_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_file',
            new_name='file',
        ),
    ]
