# Generated by Django 4.2.5 on 2023-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_rename_submission_file_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(),
        ),
    ]
